name: WorldInfo
description: Provides plugin channel messages to mods for world information.
author: Chris (Coaster3000 | Coaster4321)
website: www.github.com/coaster3000/WorldInfo
version: ${project.version}
main: tk.coaster3000.worldinfo.WorldInfoPlugin
metrics: true
commands:
    reloadWorldInfo:
        description: Execute the current debug code.
        